name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ 2.7.2, 3.0, jruby-9.2.14.0 ]
        neo4j: [ 3.5.26, 4.0.11 ]
      env:
        NEO4J_EDITION_FLAG: -e
        NEO4J_VERSION: ${{ matrix.neo4j }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - uses: BSFishy/pip-action@v1
          editable: git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
      - name: Setup Env
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'


      - name: Setup Neo4j
        run: |
          neoctrl-install $NEO4J_EDITION_FLAG $NEO4J_VERSION servers
          if [ -n "$NEO4J_EDITION_FLAG" ]; then NEO4J_EDITION=enterprise; else NEO4J_EDITION=community; fi
          NEO4J_DIR=servers/neo4j-$NEO4J_EDITION-$NEO4J_VERSION
          neoctrl-configure $NEO4J_DIR dbms.memory.pagecache.size=600m dbms.memory.heap.max_size=600m dbms.memory.heap.initial_size=600m dbms.directories.import= dbms.connectors.default_listen_address=::
          neoctrl-set-initial-password password $NEO4J_DIR
          neoctrl-start $NEO4J_DIR
          wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-18.04.deb
          sudo dpkg -i seabolt-1.7.4-Linux-ubuntu-18.04.deb

      - name: Install dependencies
        run: bin/setup
      - name: Run tests
        run: bundle exec rspec
